// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDT3OcfnZUJX77ksfmTMmWJk2sjsfbh5o',
    appId: '1:791062289580:web:6d3ed40331cb174ecc1309',
    messagingSenderId: '791062289580',
    projectId: 'wildcapital-6a6a5',
    authDomain: 'wildcapital-6a6a5.firebaseapp.com',
    databaseURL: 'https://wildcapital-6a6a5-default-rtdb.firebaseio.com',
    storageBucket: 'wildcapital-6a6a5.appspot.com',
    measurementId: 'G-17G2GCQYV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqR3LWuXdOr8hp-NfEv5IJ30Jvwrmh-U',
    appId: '1:791062289580:android:17bd447bb88bedc0cc1309',
    messagingSenderId: '791062289580',
    projectId: 'wildcapital-6a6a5',
    databaseURL: 'https://wildcapital-6a6a5-default-rtdb.firebaseio.com',
    storageBucket: 'wildcapital-6a6a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2IkvHKJfNEHLGsFgNVtLi6k00UieWBrA',
    appId: '1:791062289580:ios:6ed13e592404d55ecc1309',
    messagingSenderId: '791062289580',
    projectId: 'wildcapital-6a6a5',
    databaseURL: 'https://wildcapital-6a6a5-default-rtdb.firebaseio.com',
    storageBucket: 'wildcapital-6a6a5.appspot.com',
    iosBundleId: 'com.example.wildcapital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2IkvHKJfNEHLGsFgNVtLi6k00UieWBrA',
    appId: '1:791062289580:ios:e3cc2d2a60ae33eacc1309',
    messagingSenderId: '791062289580',
    projectId: 'wildcapital-6a6a5',
    databaseURL: 'https://wildcapital-6a6a5-default-rtdb.firebaseio.com',
    storageBucket: 'wildcapital-6a6a5.appspot.com',
    iosBundleId: 'com.example.wildcapital.RunnerTests',
  );
}
